config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'dashboards#index'
  resources :users
  resources :dashboards, shallow:true  do
    resources :tickets
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :ticket_watchers, dependent: :destroy, foreign_key: 'ticket_id'
  has_many :users, through: :ticket_watchers
  accepts_nested_attributes_for :ticket_watchers, allow_destroy: true

  belongs_to :dashboard, inverse_of: :tickets

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
  	@tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new
    @ticket.ticket_watchers.build
  end

  def create
    @dashboard = Dashboard.find_by(id: params[:dashboard_id])
    @ticket = @dashboard.tickets.build(tickets_params)
    logger.debug @ticket.errors.inspect
    if @ticket.save
      logger.debug @ticket.errors.inspect
      redirect_to dashboard_path(id: @ticket.dashboard_id), notice: 'チケットの作成に成功しました'
    else
      logger.debug @ticket.errors.inspect
      redirect_to new_dashboard_ticket_path, alert: 'チケットの作成に失敗しました'
    end
  end

  def show
  	@ticket = Ticket.find(params[:id])
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket =  Ticket.find(params[:id])
    if @ticket.update_attributes(tickets_params)
      redirect_to dashboards_path(@ticket.dashboard_id) , notice: 'ユーザーの更新に成功しました'
    else
      render 'edit'
    end
  end

  def destroy
    Ticket.find(params[:id]).destroy
    flash[:success] = "Ticket deleted"
    redirect_to dashboard_ticket_path
  end

  private

  def tickets_params
    params.require(:ticket).permit(:category, :title, :comment_descriptive, :comment_summary, :status, :PIC, :related_ticket1,:related_ticket2,:related_ticket3, :start_date, :due_date, :progress_rate, { :user_ids=> [] })
  end

end

app/views/tickets/edit.html.erb
<body>
   <h1 class="text-center my-3">チケット</h1>

   <div class="container">
   <div class="card mx-auto col-8 float-center bg-secondary mb-5 my-3">
   <article class="card-body py-3">
     <%= form_for(@ticket) do |f| %>

        <%= f.label :category, "カテゴリ" , class: 'form-group py-1' %><br>
        <%= f.select :category, ["要件定義", "設計", "開発", "単体テスト", "結合テスト", "ユーザーテスト"], {}, class: 'form-control' %>

        <%= f.label :title, "題名", class: 'form-group py-1' %><br>
        <%= f.text_field :title, placeholder: '題名を入力してください。',class: 'form-control' %>

        <%= f.label :comment_summary, "説明大項目", class: 'form-group py-1' %><br>
        <%= f.text_area :comment_summary, placeholder: 'タスク進捗状況の概要を記載してください。',class: 'form-control' %>

        <%= f.label :comment_descriptive, "説明小項目", class: 'form-group py-1' %><br>
        <%= f.text_area :comment_descriptive, placeholder: 'タスク進捗状況の詳細を記載してください。',class: 'form-control' %>

        <%= f.label :status, "ステータス", class: 'form-group py-1' %><br>
        <%= f.select :status, ["未着手", "遅延", "予定通り", "前倒し"],{}, class: 'form-control'%>

        <%= f.label :PIC, "担当者", class: 'form-group py-1' %><br>
        <%= f.collection_select :PIC, User.all, :id, :surname,class: 'form-control' %><br>

        <%= f.label :related_ticket1, "関連チケット1", class: 'form-group py-1' %><br>
        <%= f.text_area :related_ticket1, placeholder: '前後関係のあるタスクを入力してください。',class: 'form-control' %>

        <%= f.label :related_ticket2, "関連チケット2", class: 'form-group py-1' %><br>
        <%= f.text_area :related_ticket2, placeholder: '前後関係のあるタスクを入力してください。',class: 'form-control' %>

        <%= f.label :related_ticket3, "関連チケット3", class: 'form-group py-1' %><br>
        <%= f.text_area :related_ticket3, placeholder: '前後関係のあるタスクを入力してください。',class: 'form-control' %>

        <%= f.label :start_date, "開始日", class: 'form-group py-1' %><br>
        <%= f.date_field :start_date, placeholder: '開始日を入力してください。',class: 'form-control' %>

        <%= f.label :due_date, "期日", class: 'form-group py-1' %><br>
        <%= f.date_field :due_date, placeholder: '期日を入力してください。',class: 'form-control' %>


        <%= f.label :progress_rate, "進捗率", class: 'form-group py-1' %><br>
        <%= f.select :progress_rate, ["0%", "30%", "50%", "80%","100%"],{}, class: 'form-control'%>


        <%= f.label :users,"ウォッチャー", class: 'form-group py-1' %><br>
     <%= f.collection_check_boxes(:user_ids, User.all, :id, :surname ) do |t|  %>
       <% t.label { t.check_box + t.text } %>
     <% end %>

      <br><%= f.submit :class=>"btn btn-primary py-1" %>
        <%= link_to '戻る', :back, class: 'btn btn-dark' %>
    <% end %>
  </article>
　　</div> <!-- card.// -->
  </div>

</body>

app/views/tickets/index.html.erb
<head>
  <title>チケット一覧</title>
</head>
<style type="text/css">
  .statusdelay {background-color: salmon;}
  .statuscomp {background-color: gainsboro;}
  .statusdelaycomp {background-color: gainsboro;}
</style>


  <body>
    <h1 class="text-center">チケット一覧</h1>
    <div class="container">
      <table class="table">
        <thead>
          <tr>
            <th>id</th>
            <th>カテゴリ</th>
            <th>題名</th>
            <th>担当者</th>
            <th>ステータス</th>
            <th>開始日</th>
            <th>期日</th>
            <th>進捗率</th>
            <th>ウォッチャー</th>
            <th>操作</th>
        </thead>
        <tbody id = ticketlist>
          <% @tickets.each do |ticket| %>
            <tr>
              <th><%= ticket.id %></th>
              <th><%= ticket.category %></th>
              <th><%= ticket.title %></th>
              <th><%= ticket.PIC %></th>
              <th><%= ticket.status %></th>
              <th><%= ticket.start_date %></th>
              <th><%= ticket.due_date %></th>
              <th><%= ticket.progress_rate %></th>
              <th><%= ticket.watcher %></th>

              <th>
                <%= link_to '詳細', ticket_path(ticket), class: "btn btn-outline-info mb-1" %>
                <!-- TODO 削除機能の実装 -->
                <%= link_to '削除', ticket_path(ticket), method: :delete, class: "btn btn-outline-danger mb-1" %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </body>

app/views/tickets/new.html.erb
  <body>
    <h1 class="text-center my-3">チケット登録</h1>

    <div class="container">
    <div class="card mx-auto col-8 float-center bg-secondary mb-5 my-3">
    <article class="card-body py-3">
     <%= form_for @ticket , url: { action: "create" } do |f| %>

     <%= f.label :category, "カテゴリ" , class: 'form-group py-1' %><br>
     <%= f.select :category, ["要件定義", "設計", "開発", "単体テスト", "結合テスト", "ユーザーテスト"], {}, class: 'form-control' %>

     <%= f.label :title, "題名", class: 'form-group py-1' %><br>
     <%= f.text_field :title, placeholder: '題名を入力してください。',class: 'form-control' %>

     <%= f.label :comment_summary, "説明大項目", class: 'form-group py-1' %><br>
     <%= f.text_area :comment_summary, placeholder: 'タスク進捗状況の概要を記載してください。',class: 'form-control' %>

     <%= f.label :comment_descriptive, "説明小項目", class: 'form-group py-1' %><br>
     <%= f.text_area :comment_descriptive, placeholder: 'タスク進捗状況の詳細を記載してください。',class: 'form-control' %>

     <%= f.label :status, "ステータス", class: 'form-group py-1' %><br>
     <%= f.select :status, ["未着手", "遅延", "予定通り", "前倒し"],{}, class: 'form-control'%>

     <%= f.label :PIC, "担当者", class: 'form-group py-1' %><br>
     <%= f.collection_select :PIC, User.all, :id, :surname,class: 'form-control' %><br>

     <%= f.label :related_ticket1, "関連チケット1", class: 'form-group py-1' %><br>
     <%= f.text_area :related_ticket1, placeholder: '前後関係のあるタスクを入力してください。',class: 'form-control' %>

     <%= f.label :related_ticket2, "関連チケット2", class: 'form-group py-1' %><br>
     <%= f.text_area :related_ticket2, placeholder: '前後関係のあるタスクを入力してください。',class: 'form-control' %>

     <%= f.label :related_ticket3, "関連チケット3", class: 'form-group py-1' %><br>
     <%= f.text_area :related_ticket3, placeholder: '前後関係のあるタスクを入力してください。',class: 'form-control' %>

     <%= f.label :start_date, "開始日", class: 'form-group py-1' %><br>
     <%= f.date_field :start_date, placeholder: '開始日を入力してください。',class: 'form-control' %>

     <%= f.label :due_date, "期日", class: 'form-group py-1' %><br>
     <%= f.date_field :due_date, placeholder: '期日を入力してください。',class: 'form-control' %>


     <%= f.label :progress_rate, "進捗率", class: 'form-group py-1' %><br>
     <%= f.select :progress_rate, ["0%", "30%", "50%", "80%","100%"],{}, class: 'form-control'%>


     <%= f.label :users %><br>
  <%= f.collection_check_boxes(:user_ids, User.all, :id, :surname ) do |t|  %>
    <% t.label { t.check_box + t.text } %>
  <% end %>


   <%= f.submit :class=>"btn btn-primary my-2" %>
     <%= link_to '戻る', dashboards_path(@ticket.dashboard_id), class: 'btn btn-dark my-2' %>

 <% end %>


    </article>
　　</div> <!-- card.// -->
    </div>

  </body>

app/views/tickets/show.html.erb
<body>
   <h1 class="text-center my-3">チケット詳細</h1>

   <div class="container">
   <div class="card mx-auto col-8 float-center bg-secondary mb-5 my-3">
   <article class="card-body py-3">
     <%= form_for(@ticket) do |f| %>

     <%= f.label :category, "カテゴリ" , class: 'form-group py-1' %><br>
     <%= @ticket.category %><br>

     <%= f.label :title, "題名", class: 'form-group py-1' %><br>
     <%= @ticket.title %><br>

     <%= f.label :comment_summary, "説明大項目", class: 'form-group py-1' %><br>
     <%= @ticket.comment_summary %><br>

     <%= f.label :comment_descriptive, "説明小項目", class: 'form-group py-1' %><br>
     <%= @ticket.comment_descriptive %><br>

     <%= f.label :status, "ステータス", class: 'form-group py-1' %><br>
     <%= @ticket.status %><br>

     <%= f.label :PIC, "担当者", class: 'form-group py-1' %><br>
     <%= @ticket.PIC %><br>

     <%= f.label :related_ticket1, "関連チケット1", class: 'form-group py-1' %><br>
     <%= @ticket.related_ticket1 %><br>

     <%= f.label :related_ticket2, "関連チケット2", class: 'form-group py-1' %><br>
     <%= @ticket.related_ticket2 %><br>

     <%= f.label :related_ticket3, "関連チケット3", class: 'form-group py-1' %><br>
     <%= @ticket.related_ticket3 %><br>

     <%= f.label :start_date, "開始日", class: 'form-group py-1' %><br>
     <%= @ticket.start_date %><br>

     <%= f.label :due_date, "期日", class: 'form-group py-1' %><br>
     <%= @ticket.due_date %><br>

     <%= f.label :progress_rate, "進捗率", class: 'form-group py-1' %><br>
     <%= @ticket.progress_rate %><br>

     <%= f.label :watcher, "チケットのウォッチャー", class: 'form-group py-1' %><br>
     <p>今はユーザーのIDのみを配列で表示</p>
     <%= @ticket.user_ids %><br>
         <% end %>

     <%= link_to '編集', edit_ticket_path(@ticket), class: "btn btn-outline-info my-1 mp-1" %>
     <%= link_to '戻る', :back, class: 'btn btn-dark' %>



   </article>
　　</div> <!-- card.// -->
   </div>

 </body>