config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'dashboards#index'
  resources :users
  resources :dashboards, shallow:true  do
    resources :tickets
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  has_many :teams, dependent: :destroy, foreign_key: 'dashboard_id'
  has_many :users, through: :teams
  accepts_nested_attributes_for :teams, allow_destroy: true

  has_many :tickets, dependent: :destroy,inverse_of: :dashboard

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def index
		@dashboards = Dashboard.all.includes(:users)
		@tickets = Ticket.all
	end

	def new
		@dashboard = Dashboard.new
		@dashboard.teams.build
		logger.debug @dashboard.errors.inspect
	end

	def create
		@dashboard = Dashboard.new(dashboards_params)
		if @dashboard.save
			logger.debug @dashboard.errors.inspect
			redirect_to :action => "show", :id => @dashboard[:id]
		else
			logger.debug @dashboard.errors.inspect
			redirect_to dashboards_new_path, alert: 'ダッシュボードの作成に失敗しました'
		end
	end

	def show
		@dashboard = Dashboard.find(params[:id])
		@tickets = Ticket.all
	end

		def edit
			@dashboard = Dashboard.find(params[:id])
		end

		def destroy
			Dashboard.find(params[:id]).destroy
			flash[:success] = "Dashoboard is deleted"
			redirect_to dashboards_path
		end

		def update
			@dashboard = Dashboard.find(params[:id])
			#編集データの取
			if @dashboard.update(dashboards_params)
			#updateが完了したら一覧ページへリダイレクト
			redirect_to dashboard_path(@dashboard)
		else
			render 'edit'
		end

		end


		private

		def dashboards_params
			params.require(:dashboard).permit(:name, :notice,{ :user_ids=> [] }, ticket_attributes: [:id])
		end

	end

app/views/dashboards/edit.html.erb
  <body>
    <h1 class="text-center my-3">　ダッシュボード編集</h1>

    <div class="container">
    <div class="card mx-auto col-8 float-center bg-secondary mb-5 my-3">
    <article class="card-body py-3">
     <%= form_for@dashboard do |f| %>

     <%= f.label :name, "名前" , class: 'form-group py-1' %><br>
     <%= f.text_area :name, placeholder: 'ダッシュボードの名前を記入してください',class: 'form-control' %>

     <%= f.label :notiece, "お知らせ", class: 'form-group py-1' %><br>
     <%= f.text_field :notice, placeholder: 'お知らせを記入してください',class: 'form-control' %>

   <%= f.submit :class=>"btn btn-primary my-2" %>
     <%= link_to '戻る', :back, class: 'btn btn-dark my-2' %>

 <% end %>


    </article>
　　</div> <!-- card.// -->
    </div>

  </body>

app/views/dashboards/index.html.erb
<body>
<div class="row">
  <h1 class="col-12 text-center ">　参加中ダッシュボード</h1>
</div>

<div class="row">
    <%= link_to '新規作成', new_dashboard_path, class: "mx-auto btn btn-outline-info btn-md " %>
</div>

    <div class="row">

  <% @dashboards.each do |d| %>
  <% lis = d.user_ids %>
  <% if lis.include?(current_user.id) %>

  <div class="card col-sm-5 float-left bg-secondary mb-5 m-3">
    <div class="card-body py-3">

      <p><%= d.name %></p><br>
      <p><%= d.notice %></p><br>

      <%= link_to '詳細', dashboard_path(d.id), class: "btn btn-outline-info my-1 mp-1" %>
      <%= link_to '削除', dashboards_path(d.id), method: :delete, class: "btn btn-outline-danger mb-1" %>
      <%= link_to '戻る', :back, class: 'btn btn-dark my-2'%>

    </div>
  </div>

  <% end %>
  <% end %>
    </div>
</body>

app/views/dashboards/new.html.erb
<body>
  <h1 class="text-center my-3">　ダッシュボード登録</h1>

  <div class="container">
  <div class="card mx-auto col-8 float-center bg-secondary mb-5 my-3">
  <article class="card-body py-3">
   <%= form_for @dashboard ,:url => {:action => 'create'} do |f| %>

   <%= f.label :name, "名前" , class: 'form-group py-1' %><br>
   <%= f.text_field :name, placeholder: 'ダッシュボードの名前を記入してください',class: 'form-control' %>

   <%= f.label :notiece, "題名", class: 'form-group py-1' %><br>
   <%= f.text_field :notice, placeholder: 'お知らせを記入してください',class: 'form-control' %>

   <%= f.label :users %><br>
   <%= f.collection_check_boxes(:user_ids, User.all, :id, :surname ) do |t|  %>
  <% t.label { t.check_box + t.text } %>
  <% end %>
 <%= f.submit :class=>"btn btn-primary my-2" %>
   <%= link_to '戻る', :back, class: 'btn btn-dark my-2' %>

<% end %>


  </article>
　　</div> <!-- card.// -->
  </div>

</body>

app/views/dashboards/show.html.erb
  <body>
    <h1 class="text-center">ダッシュボード</h1>

      <div　class="text-left">


      </div>
  <% if can? :crud, @dashboard %>


        <form>
          <div class="mx-auto col-9">
          <%= form_for @dashboard do |f| %>
             <%= f.label :notice, "お知らせ", class: 'h2 form-group py-1' %><br>
             <%= @dashboard.notice %>
             <%= @dashboard.id %><br>

            　<%= link_to '編集', edit_dashboard_path(id: @dashboard), class: "btn btn-outline-info my-1 mp-1" %>
          <% end %>
          </div>
        </form><br>




        <h2 class="col-9 mx-auto text-left">要確認チケット</h2>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>カテゴリ</th>
        <th>題名</th>
        <th>担当者</th>
        <th>ステータス</th>
        <th>開始日</th>
        <th>期日</th>
        <th>進捗率</th>
        <th>ウォッチャー</th>
        <th>操作</th>
    <tbody>
      <% @tickets.each do |ticket| %>
      <% lis = ticket.user_ids %>
      <% if lis.include?(current_user.id) %>
        <tr>
          <th><%= ticket.id %></th>
          <th><%= ticket.category %></th>
          <th><%= ticket.title %></th>
          <th><%= ticket.PIC %></th>
          <th><%= ticket.status %></th>
          <th><%= ticket.start_date %></th>
          <th><%= ticket.due_date %></th>
          <th><%= ticket.progress_rate %></th>
          <th><%= ticket.watcher %></th>
          <th>
            <%= link_to '詳細', ticket_path(ticket), class: "btn btn-outline-info my-1 mp-1" %>
            <%= link_to '削除', ticket_path(ticket), method: :delete, class: "btn btn-outline-danger mb-1" %>
          </th>
        </tr>
        <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>

      </div>
  </body>
</html>