config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'dashboards#index'
  resources :users
  resources :dashboards, shallow:true  do
    resources :tickets
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <a class="navbar-brand" href="/">
    <%= image_tag 'TAS.png', class: "float-left", alt: "" %>
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">

    <span class="navbar-toggler-icon"></span>

  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

    <div class="navbar-nav ml-auto navbar-dark bg-dark">
    <% if controller.controller_name == "dashboards" && controller.action_name == "show"%>
    <%= link_to 'ダッシュボード', root_path, class: "nav-item mr-auto nav-link" %>
    <%= link_to 'チケット登録', new_dashboard_ticket_path(@dashboard.id), class: "nav-item nav-link" %>
    <%= link_to '管理画面', users_path, class: "nav-item nav-link" %>
    <% else %>
    <%= link_to 'ダッシュボード', root_path, class: "nav-item mr-auto nav-link" %>
    <%= link_to '管理画面', users_path, class: "nav-item nav-link" %>
    <% end %>
    </div>

  </div>

</nav>

<style>

  body {
      color: #ffffff;
      background-color: #303030;
  }

</style>

  <title>チケット作成</title>
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task4U</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <% if user_signed_in? %>
      <% if user_signed_in? %>
        <%= render 'layouts/header' %>
      <% end %>
    <% end %>
  </header>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
  <footer>
    <nav class="navbar navbar-dark bg-dark justify-content-end fixed-bottom">
    <% if user_signed_in? %>
    <span class="navbar-brand">
      <%= link_to "ログアウト", destroy_user_session_path, class: "btn btn-outline-light", method: :delete %>
    </span>
    <% end %>
    </nav>
  </footer>
</html>